{-# LANGUAGE TemplateHaskell #-}
{-# OPTIONS_GHC -fno-warn-orphans #-}

module Main where

import Data.Aeson.TypeScript.TH
import Network.URI

import Recalc.Server.TH
import Recalc.Server.TypeScript
import Recalc.Univer.Protocol

instance TypeScript URI where
  getTypeScriptType _ = "string"

instance TypeScript Cells where
  getTypeScriptType _ = "IObjectMatrixPrimitiveType<Nullable<ICellData>>"

$(deriveTypeScriptProtocolWithout ''SpreadsheetProtocol [''Cells])

main :: IO ()
main = do
  putStrLn "/** this file is auto-generated by src/ts/Main.hs */\n"
  putStrLn . formatTSDeclarations $ typeScriptInterface @SpreadsheetProtocol
