module Main where

main :: IO ()
main = putStrLn tsCode

tsCode :: String
tsCode =
  unlines
    [ "/** this file is auto-generated by src-ts/Main.hs */\n"
    , "type MethodType<T1, T2> = IMethodType<T1, T2>;\n"
    , "interface IMethodType<T1, T2> {"
    , "  params: T1;"
    , "  result: T2;"
    , "}\n"
    , "type OpenParams = IOpenParams;\n"
    , "interface IOpenParams {"
    , "  uri: string;"
    , "  sheetOrder: [string, string][];"
    , "}\n"
    , "type CloseParams = ICloseParams;\n"
    , "interface ICloseParams {"
    , "  uri: string;"
    , "}\n"
    , "type SaveParams = ISaveParams;\n"
    , "interface ISaveParams {"
    , "  uri: string;"
    , "}\n"
    , "interface SpreadsheetProtocol {"
    , "  \"open\": MethodType<OpenParams, string>;"
    , "  \"close\": MethodType<CloseParams, void>;"
    , "  \"save\": MethodType<SaveParams, void>;"
    , "}"
    ]
