name: Nix Check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

concurrency:
  group: recalc-check-${{github.ref}}
  cancel-in-progress: true

jobs:
  nix-check:
    name: Nix Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Nix
        uses: cachix/install-nix-action@v27

      - name: Set Up Cachix
        uses: cachix/cachix-action@v15
        with:
          name: recalc-cache

      - name: Check
        run: nix --accept-flake-config flake check
